language: node_js

branches:
  # Only run Travis on:
  #   A) Commits made directly to the `master` branch (i.e., merged PRs); and
  #   B) PRs that will eventually be merged into `master`.
  # This prevents excessive resource usage and CI slowness.
  only:
    - master

before_install:
  # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
  - source scripts/travis-env-vars.sh

install:
  - if has_testable_files; then npm install; fi
  # Noisy output, but useful for debugging npm package dependency version issues:
  #- npm ls

matrix:
  include:

  - node_js: 8
    env:
      - TEST_SUITE=lint
    script:
      - if has_testable_files; then npm run lint; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=unit
    addons:
      sauce_connect: true
    script:
      - if has_testable_files; then npm run test:unit && npm run posttest; else log_untestable_files; fi
    after_success:
      - codecov

  - node_js: 8
    env:
      - TEST_SUITE=closure
      - CLOSURE=1
    script:
      - if has_testable_files; then npm run test:closure; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=site-generator
    script:
      - if has_testable_files; then npm run test:site; else log_untestable_files; fi

  - node_js: 8
    env:
      - TEST_SUITE=screenshot
    git:
      depth: 200
    before_install: # Override global settings
      # Source the scripts to export their env vars. See https://superuser.com/a/176788/62792
      - source scripts/travis-env-vars.sh
      - source test/screenshot/infra/commands/travis.sh
    install: # Override global settings
      - npm install
      # Noisy output, but useful for debugging npm package dependency version issues:
      #- npm ls
    script:
      - npm run screenshot:test
